name: churchappenings
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+25

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
  flutter_staggered_grid_view: ^0.6.2
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.11
  flutter_cache_manager: ^3.3.1
  intl: ^0.18.1
  google_fonts: ^4.0.4
  dropdown_search: ^5.0.6
  flutter_svg: ^0.23.0+1
  flutter_quill: ^6.4.4
  flutter_html: ^2.2.1
  uuid: ^3.0.7
  syncfusion_flutter_gauges: ^20.4.48
  logger: ^1.4.0
  html_editor_enhanced: ^2.5.1
  # FireFlutter
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  firebase_messaging: ^14.6.4
  flutter_local_notifications: ^8.2.0
  google_sign_in: ^6.1.4
  cloud_firestore: ^4.8.2
  cloud_functions: ^4.3.3
  calendar_date_picker2: ^0.5.2

  # GraphQL and REST
  hasura_connect: ^4.0.0+4

  #local storage
  shared_preferences: ^2.2.0

  # Google place
  google_place: ^0.4.7
  geolocator: ^9.0.2
  image_picker: ^1.0.0
  firebase_storage: ^11.2.4
  google_maps_flutter: ^2.2.2

  # QR Code
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1

  # Device information
  device_info_plus: ^8.2.2
  loading_animation_widget: ^1.2.0+4
  firebase_database: ^10.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   path_provider: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
