name: churchappenings
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+22

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.2.1
  get: ^4.6.5
  flutter_staggered_grid_view: ^0.6.2
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.5
  flutter_cache_manager: ^3.3.0
  intl: ^0.18.1
  google_fonts: ^4.0.4
  dropdown_search: ^5.0.2
  flutter_svg: ^2.0.5
  flutter_quill: ^6.4.4
  flutter_html: ^3.0.0-alpha.5
  uuid: ^3.0.6
  syncfusion_flutter_gauges: ^21.2.4
  logger: ^1.3.0
  # FireFlutter
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1
  firebase_messaging: ^14.1.4
  flutter_local_notifications: ^14.0.0+1
  google_sign_in: ^6.1.0
  cloud_firestore: ^4.2.0
  cloud_functions: ^4.0.6
 
  

  # GraphQL and REST
  hasura_connect: ^4.0.0+4

  #local storage
  shared_preferences: ^2.0.15

  # Google place
  google_place: ^0.4.7
  geolocator: ^9.0.1
  image_picker: ^0.8.5+3
  firebase_storage: ^11.0.8

  # QR Code
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1

  # Device information
  device_info_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   path_provider: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/

